<?php

namespace TestDummy;


use Cake\TestSuite\IntegrationTestCase;

abstract class BaseTestCase extends IntegrationTestCase
{
    protected $factory;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        //Load factories
        $this->factory = Definition::getInstance();
        $this->factory->load(realpath(CONFIG. 'Factories'));

    }

}